# Settings for slurm
# https://github.com/snakemake/snakemake-executor-plugin-slurm/blob/main/docs/further.md
default-resources:
  slurm_partition: "your_partition"
  slurm_account:   "your_account"
  runtime: 480
  mem_mb: None
  mem_mb_per_cpu: 5000

set-resources:
  trim_reads_pe:
    cpus_per_task: 4

# Snakemake settings used for our purposes
# https://snakemake.readthedocs.io/en/stable/executing/cli.html
# restart-times: 3
max-jobs-per-second: 1
max-status-checks-per-second: 1
seconds-between-status-checks: 1200
local-cores: 1
latency-wait: 60
use-conda: True
jobs: 100
# keep-going: True
rerun-incomplete: True
printshellcmds: True
