# ==================================================================================================
#     Header
# ==================================================================================================

name: ci
on:
  pull_request:
  push:
    branches:
      - master

# ==================================================================================================
#     Jobs
# ==================================================================================================

jobs:
  run-test-case:
    runs-on: ${{ matrix.os }}

    # ==========================================================================
    #     Matrix
    # ==========================================================================

    strategy:
      fail-fast: false

      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          # - ubuntu-22.04
          # - ubuntu-20.04
          # - macos-12
          # - macos-11

        # Test cases as listed in test/cases/*.txt
        case: [ base ]
        # case: [
        #   base, calling-bcftools-1, calling-bcftools-2, calling-bcftools-3, calling-bcftools-4,
        #   calling-freebayes-1, calling-freebayes-2, calling-freebayes-3, calling-haplotypecaller-1,
        #   calling-haplotypecaller-2, calling-haplotypecaller-3, calling-haplotypecaller-4,
        #   duplicates-dedup-1, duplicates-dedup-2, hafpipe-1, hafpipe-2, hafpipe-3, hafpipe-4,
        #   mapping-bowtie2-1, mapping-bowtie2-2, mapping-bwaaln-1, mapping-bwaaln-2,
        #   mapping-bwaaln-3, mapping-bwaaln-4, mapping-bwa-mem-1, mapping-bwa-mem2-1,
        #   mapping-bwa-mem2-2, pileup-1, trimming-adapterremoval-1, trimming-adapterremoval-2,
        #   trimming-adapterremoval-3, trimming-cutadapt-1, trimming-cutadapt-2, trimming-fastp-1,
        #   trimming-fastp-2, trimming-fastp-3, trimming-seqprep-1, trimming-seqprep-2,
        #   trimming-skewer-1, trimming-skewer-2
        # ]

    # ==========================================================================
    #     Steps
    # ==========================================================================

    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2.2.0
        with:
          # We need mamba here already, otherwise we run into
          # https://github.com/conda-incubator/setup-miniconda/issues/262
          mamba-version: "*"
          environment-file: envs/grenepipe.yaml
          activate-environment: grenepipe

      # Manually create the conda env.
      # Not needed at the moment, as the above setup works fine. Keeping this here for reference.
      # - name: Install Conda Env
      #   shell: bash -el {0}
      #   run: |
      #     mamba env create -f envs/grenepipe.yaml -n grenepipe
      # The in the run step:
      # conda activate grenepipe

      - name: Run Test
        # Need to specify the shell explicitly.
        # https://github.com/marketplace/actions/setup-miniconda#important
        shell: bash -el {0}
        run: |
          ./test/run.sh ${{ matrix.case }}
